# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - limb1_to_base_link
      - limb2_to_limb1
      - limb3_to_limb2
      - limb4_to_limb3
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joints:
      - limb5_to_limb4
      - left_hand_to_limb5
      - right_hand_to_limb5
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity